### ISSUE TITLE
Support platform Web Components

### ISSUE THREAD

**Issue by mkxml** [z-kit/z-hello#2]
The component should be exported complying to the current [Web Components](https://www.w3.org/standards/techs/components#w3c_all) spec.

- [x] Custom Elements V1;
- [x] Shadow DOM v1 (open, encapsulating CSS);
- [x] HTML Imports (easy component registration);

**Comment by mkautzmann** [comment]
Support is being added in `src/webcomponents`

**Comment by mkautzmann** [comment]
Should close this when demos and info on README are available

**Comment by mkxml** [comment]
Done!
